### ISSUE TITLE
[BUG] Not catching DB url resolve

### ISSUE THREAD

**Issue by slimshizn** [Boerderij/Varken#103]
**Describe the bug**
Varken docker shuts down after trying to download the latest GeoLite2, and will not stay on. Varken will not work without it.

**To Reproduce**
1. ... Restart Varken container.

**Expected behavior**

Varken to start, without error if possible and stay on.

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04.1 or Docker:Tag] Unraid 6.6.6 Linux 4.18.20 Python 3.7.2
 - Version [e.g. v1.1]  Varken 1.6.4-master

**Additional context**

> 2019-02-10 23:35:36 : ERROR : helpers : Could not find GeoLite2 DB as: /config/GeoLite2-City.mmdb
> 
> 2019-02-10 23:35:36 : INFO : helpers : Downloading GeoLite2 from http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz
> Traceback (most recent call last):
> File "/app/varken/helpers.py", line 39, in update
> dbdate = date.fromtimestamp(stat(self.dbfile).st_mtime)
> FileNotFoundError: [Errno 2] No such file or directory: '/config/GeoLite2-City.mmdb'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> File "/app/Varken.py", line 110, in <module>
> GEOIPHANDLER = GeoIPHandler(DATA_FOLDER)
> File "/app/varken/helpers.py", line 24, in __init__
> self.update()
> File "/app/varken/helpers.py", line 42, in update
> self.download()
> File "/app/varken/helpers.py", line 64, in download
> urlretrieve(url, tar_dbfile)
> File "/usr/local/lib/python3.7/urllib/request.py", line 247, in urlretrieve
> with contextlib.closing(urlopen(url, data)) as fp:
> File "/usr/local/lib/python3.7/urllib/request.py", line 222, in urlopen
> return opener.open(url, data, timeout)
> File "/usr/local/lib/python3.7/urllib/request.py", line 531, in open
> response = meth(req, response)
> File "/usr/local/lib/python3.7/urllib/request.py", line 641, in http_response
> 'http', request, response, code, msg, hdrs)
> File "/usr/local/lib/python3.7/urllib/request.py", line 569, in error
> 
> return self._call_chain(*args)
> File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain
> result = func(*args)
> File "/usr/local/lib/python3.7/urllib/request.py", line 649, in http_error_default
> raise HTTPError(req.full_url, code, msg, hdrs, fp)
> urllib.error.HTTPError: HTTP Error 503: Service Temporarily Unavailable

**Comment by slimshizn** [comment]
> 2019-02-10 19:47:13 : INFO : helpers : Newer GeoLite2 DB available, Updating...
> 2019-02-10 19:47:13 : INFO : helpers : Downloading GeoLite2 from http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz

This was earlier upon restart and when the errors started occurring.

**Comment by DirtyCajunRice** [comment]
summation: we need to catch db download error

**Comment by slimshizn** [comment]
Tried
starting a fresh varken instance
downgrading to 1.6.3

No luck.

**Comment by slimshizn** [comment]
Thanks for the help and fixes. Works great.
