### ISSUE TITLE
[BUG] URL not working with url base type address

### ISSUE THREAD

**Issue by saitoh183** [Boerderij/Varken#108]
**Describe the bug**
I get the following error when i start varken in docker

```
2019-02-22 01:21:17 : INFO : helpers : SONARR_SERVER_IDS : [1]
2019-02-22 01:21:17 : ERROR : iniparser : ************************ttps://server.feralhosting.com/jessy/sonarr is invalid in module [sonarr-1]! URL must host/IP and port if not 80 or 443. ie. localhost:8080
```
 With radarr it is the same issue. Both apps are running on my FeralHosting box. The URL works just fine in the browser or if i use it in Organizr with API key. I also set the ssl options to true but it is still the same problem.
 
**To Reproduce**
1. ...
2. ...
3. ...
4. ...

**Expected behavior**
No Error
**Screenshots**

**Environment (please complete the following information):**
 - OS: boerderij/varken:latest
 - Version [e.g. v1.1]

**Additional context**
Here is the config entry

```
[sonarr-1]
url = https://server.feralhosting.com/jessy/sonarr
apikey = API_KEY
ssl = true
verify_ssl = true
missing_days = 7
missing_days_run_seconds = 300
future_days = 1
future_days_run_seconds = 300
queue = true
queue_run_seconds = 300
```

**Comment by DirtyCajunRice** [comment]
Please read the wiki. This is a configuration issue.
