### ISSUE TITLE
Can't connect to InfluxDB

### ISSUE THREAD

**Issue by cm86** [Boerderij/Varken#110]
**Describe the bug**
OS: Unraid 6.6.6
Installation via Unraid GUI like described in the Wiki
Error:
The Container can't resolve InfluxDB-Host
`requests.exceptions.ConnectionError: HTTPConnectionPool(host='influxdb.domain.tld', port=8086): Max retries exceeded with url: /ping (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1543f7961128>: Failed to establish a new connection: [Errno -2] Name does not resolve'))`

**To Reproduce**
1. Install InfluxDB via Unraid GUI
2. Install Varken via Unraid GUI
3. Look into the Logfiles

![bildschirmfoto 2019-02-25 um 23 23 48](https://user-images.githubusercontent.com/14919688/53372930-6f5e5500-3954-11e9-803d-e25afa134b41.png)

I Think it's only a variable that i would set in the GUI but i don't know this variable...

Mit freundlichen Grüßen
Chris

**Comment by samwiseg0** [comment]
Please use Discord for support. https://discord.gg/VjZ6qSM
