### ISSUE TITLE
[BUG] TZDATA issue in docker images

### ISSUE THREAD

**Issue by wikkixwikki** [Boerderij/Varken#112]
**Describe the bug**
Time does not display correctly inside the container. Shows only UTC. TZDATA needs to be corrected... The current short term fix is 

**To Reproduce**
Steps to reproduce the behavior:  install and check logs for date/time it was only showing UTC
1. docker exec in
2. date
3. only shows UTC time rather than local time
4.run 
docker exec -it varken /bin/sh
apk add --no-cache tzdata
exit
docker restart varken
to fix

**Expected behavior**
Date/time should be showing the correct date/time for local/reflect what server is set to
**Screenshots**

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04.1
 - Version 1.7.3

**Additional context**

**Comment by samwiseg0** [comment]
You did not follow the issue template. The TZ can be set with the TZ env. Please read the docker documentation.
