### ISSUE TITLE
[BUG] Handle GeoIP Downloads better

### ISSUE THREAD

**Issue by samwiseg0** [Boerderij/Varken#113]
**Describe the bug**
In certain scenarios the DB would fail to download. When this happens we would get stuck in a condition were the file would be deleted but would not be able to be downloaded. Now we fail in such a way where we keep the old DB if we fail to update or download. 

Also the DB must be at least 60 days old before we attempt to update.

**Comment by slimshizn** [comment]
Thanks for the update.
