### ISSUE TITLE
[BUG] Ombi null childRequest output

### ISSUE THREAD

**Issue by 4pack** [Boerderij/Varken#119]
**Describe the bug**
When there are no denied requests in Ombi, the function *get_all_requests* errors out with the following error:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/Varken/Varken.py", line 34, in thread
    a = job()
  File "/opt/Varken/varken/ombi.py", line 105, in get_all_requests
    if show.childRequests[0]['denied']:
IndexError: list index out of range
```
This used to work in the past. The function doesn't check to see if the index actually exists before checking the value.
https://github.com/Boerderij/Varken/blob/8877b7b3c1be76f445d5637b32f4c4bef4d30928/varken/ombi.py#L105

**To Reproduce**
1. Run Ombi 3.0.4256
2. Don't deny requests
3. Run Varken
4. Everything breaks

**Expected behavior**
Ombi data is added to InfluxDB and the thread stays running.

**Environment (please complete the following information):**
 - OS: Ubuntu 16.04.5 (LXC Container)
 - Version (develop/bd98b3c)

**Additional context**
I do recall this working in the past. This seems to kill the thread preventing anything else from being written to InfluxDB.

**Comment by samwiseg0** [comment]
This may not be a bug but broken data in the API calls...Can you make these calls manually and post the data in a gist. 

It is erroring on that line because that is the first time we evaluate the data. Has nothing to do with denied requests. 

```
tv_endpoint = '/api/v1/Request/tv'
movie_endpoint = "/api/v1/Request/movie"
```

**Comment by DirtyCajunRice** [comment]
@samwiseg0 its most certainly broken data as usual. we could do a .get(key, False) tho to account for it though

**Comment by 4pack** [comment]
Sorry I didn't respond sooner. See below gist.
https://gist.github.com/4pack/1278737e4ba79eba60a8a2461a6af7c5

Looks like the denied key for TV shows is returning null, which would definitely error that if call out.

**Comment by 4pack** [comment]
This gets even more fun. One of the requested TV shows doesn't have any content in childRequests somehow. If these are skipped over (or empty data is put in place of the empty request) then it works fine. API changes are fun...
```
{
    "tvDbId": 70839,
    "imdbId": "tt0276656",
    "qualityOverride": null,
    "rootFolder": null,
    "overview": "Welcome to MTV Cribs, the most exciting way to peep into your favourite celebrity homes without getting slapped with a restraining order.",
    "title": "MTV Cribs",
    "posterPath": "https://static.tvmaze.com/uploads/images/medium_portrait/25/64588.jpg",
    "background": null,
    "releaseDate": "2000-09-20T00:00:00",
    "status": "Ended",
    "totalSeasons": 0,
    "childRequests": [],
    "id": 70839
  },
```

**Comment by samwiseg0** [comment]
Neither of these issues are API changes but rather a broken state the app has created. You might find that removing the broken data and adding it back might rectify the issue. There has to be child objects in TV shows.
