### ISSUE TITLE
[BUG] Email invitation link is for localhost

### ISSUE THREAD

**Issue by Kazz3r24** [Boerderij/Varken#123]
**Describe the bug**

When sending an invitation via smtp the email works fine so long as it's configured in defaults.ini, but the link for the invitation shows as https://localhost:<port><invite key> rather than an externally available address.

**To Reproduce**
1. ...configure smtp
2. ...attempt to send user invitation
3. ...click link in invitation
4. ...won't work unless you're on localhost

**Expected behavior**

URL show take the user to the appropriate page on Varken where they can finish creating their user account.

**Screenshots**

![image](https://user-images.githubusercontent.com/15070472/56412071-03f87b80-6251-11e9-872d-5f84f1841469.png)

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04.1 or Docker:Tag]
 - Version [e.g. v1.1]

Ubuntu Server 16.04
Grafana v6.1.4 (commit: fef1733) 
Latest version of Varken, installed it today.

**Additional context**

I sifted through the HTML code for the new_user_invite.html file and the portion that calls the URL is .LinkUrl, if I can find out where that is defined, than it should be easy enough to change it to the proper link. Unless there's a simpler/better way of doing it.

**Comment by DirtyCajunRice** [comment]
Hey! this is not a varken issue, but a grafana configuration issue. I can point you in the right direction anyhow just jump in discord.
