### ISSUE TITLE
[Feature Request] Support Specifying InfluxDB Database Name

### ISSUE THREAD

**Issue by HackedServer** [Boerderij/Varken#128]
**Is your feature request related to a problem? Please describe.**
Shared InfluxDB service where I can't choose my own database name.

**Describe the solution you'd like**
Add support for a database variable in the config file.
[influxdb]
database = database-name

**Comment by DirtyCajunRice** [comment]
we intentionally removed this long ago. i highly doubt you have any other databases named varken

**Comment by HackedServer** [comment]
As describe in the request I'm using a service that provides me with an influxdb account and a database. Its a shared service. The database name is auto-generated.

**Comment by DirtyCajunRice** [comment]
That is an unfortunate service you have. An edge case does not validate the need for something that the masses will mess up often. In its current state you will need to build from source and modify https://github.com/Boerderij/Varken/blob/8877b7b3c1be76f445d5637b32f4c4bef4d30928/varken/dbmanager.py replacing varken with the name of your db. in the appropriate lines.
