### ISSUE TITLE
The Grafana template isnt variablized properly for the Missing Movies panel[BUG]

### ISSUE THREAD

**Issue by vulcanjedi** [Boerderij/Varken#130]
**Describe the bug**
the tooltip and linkurl goto movies.yourdomain.com
And none of the variables update this properly. I had to copy of the json and reimport.
just fyi.
Line 3878/79 of JSON

**To Reproduce**
1. ...
2. ...
3. ...
4. ...

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
 - OS: [e.g. Ubuntu 18.04.1 or Docker:Tag]
 - Version [e.g. v1.1]

**Additional context**

**Comment by DirtyCajunRice** [comment]
Yep we are aware. Thanks.

**Comment by DirtyCajunRice** [comment]
Yep we are aware. Thanks.
