### ISSUE TITLE
Change logging level [Feature Request]

### ISSUE THREAD

**Issue by rssfed23** [Boerderij/Varken#135]
Is it possible to change the logging level in the config.ini file?
I may of missed it in the documentation but couldn't seem to find the right syntax (apologies in advance if it's in there!)

If it cant, then this can be treated as a feature request.

Keep up the awesome work!

**Comment by samwiseg0** [comment]
It is a command line switch. https://github.com/Boerderij/Varken/blob/master/Varken.py#L44

In the future please use our support options. https://github.com/Boerderij/Varken/wiki/Asking-for-Support
