### ISSUE TITLE
[BUG] "Missing Available" showing movies that are missing, but not available

### ISSUE THREAD

**Issue by rickylford** [Boerderij/Varken#136]
**Describe the bug**
In the "Missing Available" table, it is showing movies that are missing, but are not actually available yet (some are years away from release).

**To Reproduce**
1. View Dashboard in Grafana

**Expected behavior**
I would expect this to show movies that are missing, but have already been released either in theaters, or on BR/DVD.

**Screenshots**
![Capture](https://user-images.githubusercontent.com/929349/59561601-98782380-8fdf-11e9-95cb-af712255ff93.PNG)

**Environment (please complete the following information):**
 - OS: Docker
 - Version Latest

**Additional context**

**Comment by samwiseg0** [comment]
This is not a bug. Check your radarr settings. If the movie shows in red radarr is acutely looking for it. Make sure you change your availability setting for the movie.
