### ISSUE TITLE
[Feature Request] Support for QBittorrent

### ISSUE THREAD

**Issue by tomschlick** [Boerderij/Varken#139]
**Is your feature request related to a problem? Please describe.**
I would love to have real time stats for the number of torrents downloading/seeding/completed/failed and the throughput of each sent to InfluxDB.

**Describe the solution you'd like**
If this project is open to adding more supported services, I can craft a PR to support QBT's web interface ([which has a json based api](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-Documentation)).

**Describe alternatives you've considered**
Alternatively, I can create a separate script to track QBT on my own. Just thought it might be useful to others here.

**Comment by DirtyCajunRice** [comment]
@tomschlick Hop in discord and lets talk about it.

**Comment by DirtyCajunRice** [comment]
Closing as i never heard from tom :/. Feel free to ping me in discord.
