### ISSUE TITLE
[BUG] Varken can't run without an influxdb admin account

### ISSUE THREAD

**Issue by hashworks** [Boerderij/Varken#140]
**Describe the bug**
When running without an influxdb admin account varken fails to start, even when the database already exists and the user has write rights to the specified database.

**To Reproduce**
1. Create the varken database and user
2. Grant write access on the varken database to varken user
3. Start varken with the created user set in configuration

**Expected behavior**
Varken should not try to create the database if it already exists. If that isn't possible it should be configurable. At the very least it should not exit when it fails to create the database.

**Log**
```
Jun 22 15:04:02 hive python[7661]: 2019-06-22 15:04:02 : DEBUG : connectionpool : Starting new HTTP connection (1): ********lhost:8086
Jun 22 15:04:02 hive python[7661]: 2019-06-22 15:04:02 : DEBUG : connectionpool : http://********lhost:8086 "GET /ping HTTP/1.1" 204 0
Jun 22 15:04:02 hive python[7661]: 2019-06-22 15:04:02 : INFO : dbmanager : Influxdb version: 1.7.3
Jun 22 15:04:02 hive python[7661]: 2019-06-22 15:04:02 : DEBUG : connectionpool : http://********lhost:8086 "GET /query?q=SHOW+DATABASES&db=********arken HTTP/1.1" 200 None
Jun 22 15:04:02 hive python[7661]: 2019-06-22 15:04:02 : INFO : dbmanager : Creating ********arken database
Jun 22 15:04:02 hive python[7661]: 2019-06-22 15:04:02 : DEBUG : connectionpool : http://********lhost:8086 "POST /query?q=CREATE+DATABASE+%22********arken%22&db=********arken HTTP/1.1" 403 131
Jun 22 15:04:02 hive python[7661]: Traceback (most recent call last):
Jun 22 15:04:02 hive python[7661]:   File "/usr/lib/varken/Varken.py", line 96, in <module>
Jun 22 15:04:02 hive python[7661]:     DBMANAGER = DBManager(CONFIG.influx_server)
Jun 22 15:04:02 hive python[7661]:   File "/usr/lib/varken/varken/dbmanager.py", line 29, in __init__
Jun 22 15:04:02 hive python[7661]:     self.influx.create_database('varken')
Jun 22 15:04:02 hive python[7661]:   File "/usr/lib/python3.7/site-packages/influxdb/client.py", line 579, in create_database
Jun 22 15:04:02 hive python[7661]:     method="POST")
Jun 22 15:04:02 hive python[7661]:   File "/usr/lib/python3.7/site-packages/influxdb/client.py", line 416, in query
Jun 22 15:04:02 hive python[7661]:     expected_response_code=expected_response_code
Jun 22 15:04:02 hive python[7661]:   File "/usr/lib/python3.7/site-packages/influxdb/client.py", line 286, in request
Jun 22 15:04:02 hive python[7661]:     raise InfluxDBClientError(response.content, response.status_code)
Jun 22 15:04:02 hive python[7661]: influxdb.exceptions.InfluxDBClientError: 403: {"error":"error authorizing query: varken not authorized to execute statement 'CREATE DATABASE varken', requires admin privilege"}
Jun 22 15:04:02 hive systemd[1]: varken.service: Main process exited, code=exited, status=1/FAILURE
```

**Environment (please complete the following information):**
 - OS: Archlinux
 - Version 1.7.1

**Additional context**
Issue #53 is related. From a security standpoint it is absolutely not acceptable that an application which in the end only has to write to a single database has admin access to the whole influxdb instance.

**Comment by DirtyCajunRice** [comment]
@hashworks Could you please join our discord? You shouldnt need an admin account to run varken, the only thing you cant choose is the database name currently (as explained in #53). I want to ask some support questions before I close this out to make sure it isnt actually a bug.

**Comment by hashworks** [comment]
So apparently the influxdb user needs read access for `varken` the database so can acknowledge that it exists. Write access is not enough.

**Comment by DirtyCajunRice** [comment]
It is worth noting that in the wiki so i will do so :)
