### ISSUE TITLE
[BUG] Missing Available Movies/TV Shows does not take Monitored status into account

### ISSUE THREAD

**Issue by mikeporterdev** [Boerderij/Varken#141]
**Describe the bug**
Missing Available Movies will show movies as missing even when they are unmonitored in Radarr. This situation has only happened for me as I am using https://github.com/blacktwin/JBOPS various removing scripts, as they delete the files and set them to unmonitored after, but do not remove the Radarr entries, but this is easily possible for someone to do just using Radarr. 

**To Reproduce**
1. Add movie in Radarr
2. Set movie to unmonitored but do not remove from Radarr
3. Movie will appear in Missing Available Movies

**Expected behavior**
Would expect the movie not to appear if it is unmonitored.

**Screenshots**

**Environment (please complete the following information):**
 - OS: Docker:latest
 - Version latest

**Additional context**
Will be submitting PR shortly if agreed to be fixed

**Comment by DirtyCajunRice** [comment]
Not adding for lidarr until someone can confirm that `trackedDownloadStatus` == monitored
