### ISSUE TITLE
historical_tautulli_import.py Errors out

### ISSUE THREAD

**Issue by Dragonsys** [Boerderij/Varken#147]
When running this script I just get the following error.

Traceback (most recent call last):
  File "E:\Tools\historical_tautulli_import.py", line 7, in <module>
    from varken.iniparser import INIParser
ModuleNotFoundError: No module named 'varken'

i have tried with Varken running and not running. I don't see any config in the script to be set. I'm sure I'm missing something simple here.

**Comment by DirtyCajunRice** [comment]
I need to look at the import as i haven't touched it in a while. Ill update once i do

**Comment by DirtyCajunRice** [comment]
So currently to work the file needs to live right next to Varken.py and you need to specify the data folder. It could use an update for the env vars at some point
