### ISSUE TITLE
[Feature Request] Medusa Support

### ISSUE THREAD

**Issue by Dragonsys** [Boerderij/Varken#148]
**Is your feature request related to a problem? Please describe.**
No problem

**Describe the solution you'd like**
I would love to see if Medusa could be supported. It is very similar to SickChill (I believe they are both forked from SickRage). https://pymedusa.com/

**Describe alternatives you've considered**
I have tried using the SickChill support and just inputting my Medusa information, but it doesn't seem to work properly. I can find any information when I try making new panels in Grafana.

**Comment by DirtyCajunRice** [comment]
Medusa, unless changing their api does work. There have been many people who use it via our sickchill support. Please use discord for support
