### ISSUE TITLE
[BUG] Varker dockershuts itself down randomly 

### ISSUE THREAD

**Issue by DavidSpek** [Boerderij/Varken#152]
**Describe the bug**
On unraid running the docker, I noticed the docker sometimes randomly shut down. Upon looking in the log the following error repeats itself every 30 seconds.

`ERROR : tautulli : TypeError has occurred : __new__() got an unexpected keyword argument 'video_scan_type' while creating TautulliStream structure`

Also, another "bug" I have noticed is the "Ombi Requests Pending" monitor in the Grafana desktop does not receive any data. I tried playing around with removing some variable to try and solve the issue however the query is always empty. 

**Expected behavior**
Varker docker should not shut itself down randomly. Ombi Requests Pending in the Grafana interface should show data. 

**Environment (please complete the following information):**
 - OS: unraid
 - Version 6.7.2
 -Tautulli version v2.1.35-beta
- Ombi version 3.0.4680

**Comment by samwiseg0** [comment]
This is not a bug. There were changes to Tautulli and Varken develop has the enhancements needed.
