### ISSUE TITLE
[BUG] Medusa API wont work

### ISSUE THREAD

**Issue by juliemars** [Boerderij/Varken#158]
Hi
I have setup varken but I am unable to get Medusa working (https://github.com/pymedusa/Medusa/) the logs look ok, but when I manually go to the URL I get the following message 
"{"data": {}, "message": "param: 'type' with given value ['missed', 'today', 'soon', 'later', 'snatched']  is out of allowed range ['later', 'missed', 'soon', 'today']", "result": "error"}"

if I remove the snatched from the URL then it works fine.

Is there any way to fix this from my end or do you need to add medusa as an option?

**To Reproduce**
1. set varken
2. install Medusa
3. Configure both
4. check for api to work

**Expected behavior**
TV Shows section works

**Environment (please complete the following information):**
 - OS:  Docker:Latest
 - Version 1.74 Master
**Additional context**

**Comment by samwiseg0** [comment]
I asked you in support to provide your logs. Secondly, Medusa is not officially supported. If you read through our documentation at no point do we say we support it. Please utilize support before opening an issue.

**Comment by juliemars** [comment]
Hi I haven't used your support as discord never works for me maybe someone else? 

FaIr enough on officially supported but you do mention sickchill which is the really old unused one. Will have a look at Medusa support and see if they can amend the api or something. 

Maybe you could consider supporting it as Medusa is very popular nowadays.

Thanks
