### ISSUE TITLE
[BUG] Unifi Errors

### ISSUE THREAD

**Issue by mikestecker** [Boerderij/Varken#160]
**Describe the bug**
I cannot seem to get Unifi to work. I keep getting the following errors:

```
INFO : helpers : UNIFI_SERVER_IDS : [1],
DEBUG : iniparser : ********1.248:8443 is a valid URL in module [unifi-1].,
ERROR : unifi : Could not retrieve session cookie from UniFi Controller,
ERROR : unifi : Could not get list of sites from UniFi Controller,
INFO : __init__ : Running job Every 300 seconds do thread(<bound method UniFiAPI.get_usg_stats of <unifi-1>>) (last run: [never], next run: 2019-11-06 14:00:56),
ERROR : unifi : Attempting to reauthenticate for unifi-1,
ERROR : unifi : Could not retrieve session cookie from UniFi Controller,
ERROR : unifi : Disregarding Job get_usg_stats for unifi-1
```

**To Reproduce**
1. Configure varken.ini
2. Start varken.ini
3. Check logs

**Expected behavior**
Varken to connect to Unifi Controller and function properly

**Screenshots**

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04.1, Docker latest, Unifi Controller 5.12.22 (running on Cloud Key G2+)
 - Varken (latest docker tag)

**Additional context**
I have tried all different configurations of varken.ini with the site name capitalized and lowercase, set up a new user for varken to use, also tried my normal user/password.

Also of note, my Unifi Cloud Key G2+ does not have a TLD name, so I have configured it to connect via a static IP assigned to the Cloud Key.

EDIT: Here is my config:
```
[unifi-1]
url = internal-ip-address:8443
username = myusername
password = myuserpassword
site = default
usg_name = rt-Unifi-1
ssl = false
verify_ssl = false
get_usg_stats_run_seconds = 300
```

**Comment by Drawer** [comment]
Try setting ssl = true. 
I found that out after I visited the internal-ip-address:8443/api in the browser and it gave me the following error:

> Bad Request
> This combination of host and port requires TLS.

**Comment by DirtyCajunRice** [comment]
Please use appropriate channels (Discord) for support. Thanks!
