### ISSUE TITLE
[Feature Request] Include 'artists' count from Tautulli 

### ISSUE THREAD

**Issue by jonbackhaus** [Boerderij/Varken#163]
**Is your feature request related to a problem? Please describe.**
I would like to have an "Artists" count in Grafana. 

**Describe the solution you'd like**
[0001-Add-count-for-artists-to-InfluxDB-scrape.patch.tar.gz](https://github.com/Boerderij/Varken/files/4008278/0001-Add-count-for-artists-to-InfluxDB-scrape.patch.tar.gz)

**Describe alternatives you've considered**
N/A

**Additional context**
Patch file attached.

**Comment by jonbackhaus** [comment]
On the off-chance the attachment doesn't work: 
```
From 9eeaaf8a7626c71c6e658089aea82581982a3fdd Mon Sep 17 00:00:00 2001
From: Jonathan Backhaus <jonathan.david.backhaus@gmail.com>
Date: Sun, 29 Dec 2019 11:37:09 -0500
Subject: [PATCH] Add count for artists to InfluxDB scrape

---
 varken/tautulli.py | 1 +
 1 file changed, 1 insertion(+)

diff --git a/varken/tautulli.py b/varken/tautulli.py
index c0ec8e5..a8d677b 100644
--- a/varken/tautulli.py
+++ b/varken/tautulli.py
@@ -218,6 +218,7 @@ class TautulliAPI(object):
                 data['fields']['episodes'] = int(library['child_count'])

             elif library['section_type'] == 'artist':
+                data['fields']['artists'] = int(library['count'])
                 data['fields']['albums'] = int(library['parent_count'])
                 data['fields']['tracks'] = int(library['child_count'])
             influx_payload.append(data)
--
2.24.1
```

**Comment by samwiseg0** [comment]
In the future please put in a PR and do not just provide a patch file. That would make things a whole lot easier. 

I have added it to develop. It will be in the next release.

**Comment by jonbackhaus** [comment]
Thanks, sorry, and will-do!
