### ISSUE TITLE
[Feature Request] Optional Season and Episode numbering in Titles for TV Shows

### ISSUE THREAD

**Issue by razer86** [Boerderij/Varken#167]
When a TV Show is being played, "media_type" is set to "episode". This can be used to then capture the "parent_title" which is the season number, and "media_index" which is the episode number.

To then get to display in Grafana correctly, some minor formatting would be needed to send a new tag to Influx with the full episode string.

ie: In varken/tautulli.py somewhere before line 124

```
if session.media_type == "episode":
    season = session.parent_title.split(' ')
    #Season number padding
    season = "S"+season[1].zfill(2)

    #Episode number padding
    if len(session.media_index) == 1:
        episode = "E"+session.media_index.zfill(2)
    else:
        episode = "E"+session.media_index

    #Update title for episodes only
    full_title = session.grandparent_title+" - "+season+episode+" - "+session.title

#Keep movies titles the same
if session.media_type == "movie":
    full_title = session.full_title


#Update "tags: {" to contain the new title variable rather than session.full_title
    "title": full_title,
```
This would result in the following strings being available to be displayed in Grafana as playback progress:
```
Pokémon - S18E135 - The Final Four! (as opposed to Pokémon - The Final Four!)
Arrow - S08E07 - Purgatory (as opposed to Arrow - Purgatory)
etc

```    

The only issue is I am not sure what those fields display when playing a daily-release TV show.

**Comment by samwiseg0** [comment]
This change would go against the structure that we have already setup for Tautulli. Each value gets a corresponding field.

**Comment by razer86** [comment]
But it doesn't change your Tautulli structure at all?
The same tags are getting passed to Influx, its just checking if its tv or movie, and then wrapping the tv name to make it a little more readable.
