### ISSUE TITLE
[Feature Request] Emby Support

### ISSUE THREAD

**Issue by mpearon** [Boerderij/Varken#179]
**Is your feature request related to a problem? Please describe.**
Emby Support

**Describe the solution you'd like**
I am pretty sold out to Emby, and would love to see an integration! In their in-house forum, the Emby developers have offered API assistance to people building metrics apps.  Is this something you would consider?
Apologies for the “duplicate” issue - the others were archived, I think.

**Comment by samwiseg0** [comment]
Please see https://github.com/Boerderij/Varken/issues/72

**Comment by mpearon** [comment]
@samwiseg0 - That’s why I spun up another issue - to show there was more interest and a source of information being offered.

**Comment by samwiseg0** [comment]
As we said in that issue. We would prefer not to poll emby directly. We would like there to be a Tautulli equivalent which currently does not exist. The primary developers on this project do not use emby nor do we have any interest in doing so.

PRs are always welcome.

**Comment by mpearon** [comment]
@samwiseg0 - Looks like there is some work going on for something similar [here](https://github.com/mregni/EmbyStat).  Not sure if this would satisfy your needs or if it would be a drop-in replacement for Varken.  I’ve only just found out about that project, so I’ll dig a bit more.

Curiosity - what is your reasoning for not wanting to poll Emby and Plex directly?

**Comment by samwiseg0** [comment]
It adds overhead to the server. Secondly, Tautulli keeps much more accurate stats. From my recollection emby is similar as Plex as it does not really keep all the information. Lastly, like any other product. Keeping statistics separate from a product is typically a good idea and typically “best practice”.

**Comment by mpearon** [comment]
@samwiseg0 - That makes sense. Thank you for the information.  I’ll poke around at the other project and see if they are getting anywhere with things.  Maybe I’ll be able to lend a hand to one or both.
I **do** love a good metric collector. :)

**Comment by mpearon** [comment]
@samwiseg0 - It looks like [EmbyStat](https://github.com/mregni/EmbyStat) might be the Tautulli equivalent you've mentioned and is being actively developed.  Is this something you might consider?

**Comment by samwiseg0** [comment]
We have no plans to support it as we don’t use it and have not plans currently to start using it. We are completely open to PR request and would consider merging if someone developed and integration. 

Thanks!
