### ISSUE TITLE
[BUG]  Varken data collector fails to start on Raspbian

### ISSUE THREAD

**Issue by rnsimmons** [Boerderij/Varken#180]
**Describe the bug**
When starting the Varken data collector using "sudo python3 /opt/Varken/Varken.py", it fails to start with an error stating:

File "/opt/Varken/Varken.py", line 93, in <module>
    DBMANAGER = DBManager(CONFIG.influx_server)
  File "/opt/Varken/varken/dbmanager.py", line 19, in __init__
    version = self.influx.request('ping', expected_response_code=204).headers['X-Influxdb-Version']
  File "/usr/local/lib/python3.7/dist-packages/influxdb/client.py", line 369, in request
    raise InfluxDBClientError(err_msg, response.status_code)
influxdb.exceptions.InfluxDBClientError: 200: <!DOCTYPE html>
<html lang="en">

**To Reproduce**
1. cd /opt/Varken
2. sudo python3 /opt/Varken/Varken.py

**Expected behavior**
The collector would start running and adding data to the influxdb database.

**Environment (please complete the following information):**
 - OS: raspbian 10 (buster)
 - Raspberry pi 3+

**Additional context**

**Comment by samwiseg0** [comment]
Please do not use issues for support. Please see [Asking for Support](https://wiki.cajun.pro/books/varken/page/before-asking-for-support-make-sure-you-try-these-things-first)
