### ISSUE TITLE
[Feature Request] Aggregated stats for one library type in one stat panel

### ISSUE THREAD

**Issue by danshilm** [Boerderij/Varken#181]
**Is your feature request related to a problem? Please describe.**
I have several libraries for TV Shows and Movies and right now, if I want to have stats about all my libraries it takes up a ton of space on the Grafana dashboard since I have to have one stat panel per library on the dashboard. 

**Describe the solution you'd like**
The solution I'm looking for would be to have one measurement that adds up the stats for each library type (movies, tv shows and music) so that we can have one stat panel which shows stats for all TV Shows libraries, one for all Movies libraries and one for Music libraries.

**Describe alternatives you've considered**
I originally tried out Grafana's `Add field from calculation` introduced recently, but that can only be used when the queries are not hidden. So I can have a `Total TV Shows` field, but that requires having the amount of TV Shows per library displayed too making the stat panel very crowded. Same thing for seasons and episodes. 

**Additional context**
I actually added this to my varken setup. So I can submit a PR if you guys are okay with this.

**Comment by samwiseg0** [comment]
You can do this by modifying the panel. 

![2020-08-03_12-18-07](https://user-images.githubusercontent.com/2241731/89204155-a0987700-d583-11ea-9d43-85cc5266b1a9.png)

**Comment by danshilm** [comment]
Ah well, that should have been obvious. Thanks anyway for the help.
