### ISSUE TITLE
[Feature request] Possibility to set custom database and dropping geotagging properties

### ISSUE THREAD

**Issue by FinlandApollo** [Boerderij/Varken#184]
Hi!

I've started to use Varken, but I'd love to get ability to set custom InfluxDB database of my own and tell Varken to put thingies in there. As I have tons of databases, I'd like to keep them organized by myself. 

Also, I'd like to be able to toggle geotagging: I personally only run 1 server so I don't need geotagging properties. It could be nice if you could disable it through the config!

Nice software, very nice!

-FinlandApollo

**Comment by DirtyCajunRice** [comment]
@FinlandApollo 
1. You can set your own influxdb instance, but not the name of the db itself. There is arguably no benefit of you being able to name the database something other than what it is already named unless you had multiple instances of varken, whereas there are countless examples of users that are unable to grasp the basic concepts of a config file and giving them the ability to change a name that serves no gain adds complexity to both instructions, code, and support.
2. Geotagging has nothing to do with how many servers you run, but where the _users_ are that are using that server.
