### ISSUE TITLE
[ENHANCEMENT] Ombi 4.0 does not work with Varken

### ISSUE THREAD

**Issue by andrewhansen86** [Boerderij/Varken#186]
Logging throwing nearly continuous error over and over following recent updates pushed to apps. 

2020-12-01 12:55:14 : ERROR : ombi : TypeError has occurred : __new__() got an unexpected keyword argument 'requestStatus' while creating OmbiMovieRequest structure for movie.

To reproduce:
-Unknown at this time, but happening continuously even after a Varken restart. It does seem to stop about 60seconds after restart. However it looks to log these same errors at every startup for first 60seconds or so. 

Environment:
Docker - boerderij/varken latest

Other:
Looks to be very similar to bug #88 , and looking at varken/structures.py there is no entry for requestStatus for OmbiMovieRequest. It may be a new field.

**Comment by samwiseg0** [comment]
Please provide more details. You completely ignored the issue template. Please go back and use the template.

**Comment by andrewhansen86** [comment]
Edited original post and used issue template. Not sure how I missed the template the first time.

**Comment by samwiseg0** [comment]
What version of Ombi are you running?

**Comment by andrewhansen86** [comment]
Running 4.0.731.0

**Comment by andrewhansen86** [comment]
For Ombi I am running 4.0.731.0

**Comment by samwiseg0** [comment]
4.0 is currently unsupported. There were changes to the API and since the developer did not version the API that is why it is broken. We may eventually support it but it might be a while since 4.0 has had countless issues.

**Comment by andrewhansen86** [comment]
It is? The v4 branch is listed as the default on github now. I now it was beta for a while, but I thought it was the stable branch now. 

https://github.com/tidusjar/Ombi/branches

**Comment by samwiseg0** [comment]
I have seen many complaints about 4.0 and frankly since the developer decided to change the API and not version it like he was supposed to I have not bothered to try and fix it. They should have not just broken the API for older apps.

**Comment by andrewhansen86** [comment]
ok, good to know I may go back to the v3 branch for the time being then. Appreciate you getting to the bottom of it.

**Comment by Ornias1993** [comment]
Okey, so Varken now stopped (or is going to stop) supporting Unifi, doesn't support the latest version of Ombi AND doesn't support the latest version of InfluxDB...

Can we please just get clear information in the readme what is and isn't supported?
@samwiseg0 You keep responding that things are not supported (yet) or about to be removed and never actually documented this anywhere. We, the users, should be able to make an informed decision on using Varken.

**Comment by samwiseg0** [comment]
@Ornias1993 Issues is not the place for support. Please use our support methods if you have and issue. https://wiki.cajun.pro/books/varken/page/before-asking-for-support-make-sure-you-try-these-things-first

**Comment by Ornias1993** [comment]
@samwiseg0 I was not asking for "support", I have it running for ages already.
I was saying that the supported and not supported software versions should be documented in the readme.
