### ISSUE TITLE
[BUG] Unifi scraping not working on UDM-Pro

### ISSUE THREAD

**Issue by Ornias1993** [Boerderij/Varken#187]
Currently Unifi scraping does not seem to be working on the UDM-Pro, due to some changes in the API that are UDM-Pro Specific:
https://ubntwiki.com/products/software/unifi-controller/api

**Comment by samwiseg0** [comment]
This will not be supported in the future and I am planning on removing the functionality entirely. 

Please use this project instead. https://github.com/unifi-poller/unifi-poller

**Comment by Ornias1993** [comment]
@samwiseg0 I'm aware of Unifi-Poller, just asking because it's still part of the Grafana dashboards.
Maybe publicly state that Unifi feature is EOL and to be removed in the readme?

**Comment by samwiseg0** [comment]
Yep that is the plan as soon as I have time to work on several things on the todo list. This was a more recent decision.

Thanks for the feedback
