### ISSUE TITLE
Total Total pics Library¿?

### ISSUE THREAD

**Issue by rubenix** [Boerderij/Varken#188]
Hello, sorry If it was asked before but can't find a solid answer on that...

deployed Varken on a docker container & so far very happy with that, data from tautulli inserts just fine on influxdb.
Ive a photo Library on my plexmediaserver but it is not populated to influxdb. Only see the totalAlbums from PhotoLibrary.
Info exists on Tautulli but don't know how inject that to influxdb...

Sorry if this is not the right place to ask.
keep up that nice piece of work & thanks in advance

**Comment by samwiseg0** [comment]
In the future please use our support methods and not issues. https://wiki.cajun.pro/books/varken/page/before-asking-for-support-make-sure-you-try-these-things-first

Varken does not pull in picture metrics from Tautulli

**Comment by rubenix** [comment]
allright @samwiseg0 sure will do, sorry for opening an issue, close it down then.
couldn't find an answer thats why I asked, my apologies & thanks for answer, all clear now.
