### ISSUE TITLE
When Plex is deployed in a container with a network mode other than `host`, Worldmap details are inaccurate

### ISSUE THREAD

**Issue by jehanalvani** [Boerderij/Varken#193]
**Describe the bug**
With Plex deployed in a container, and the Plex container's network mode is anything other than `host`, the stream location data provided by Varken is inaccurate. 

**To Reproduce**
1. Deploy Plex in a container in some way (I chose Ansible), with network mode `host`
3. Deploy varken dependencies and varken with MaxMind API key.
4. Confirm stream location is accurate
5. Stop Plex container
6. Re-deploy Plex container w/ network mode other than host (`bridge` for example)
7. Refresh Varken, confirm stream location is inaccurate. 

**Expected behavior**
Expect stream location data to be accurate regardless.  

**Screenshots**

**Environment (please complete the following information):**
 - OS: Raspbian 10 (varken container host), boerderij/varken container image (sha256:c981ee2793b03be7f43b0581f117de1ff8194133ffa21bc8f606b5edaadf7cd6)
 - Version -- unsure where to find varken container version.

Happy to provide additional detail, screenshots, config if they'd be useful.

**Comment by jehanalvani** [comment]
* [This commit](https://github.com/jehanalvani/fustercluck/commit/04d2bc96cf0ed1ce9410cbcd0e72e52e8a76ee63#) has Ansible config that exhibited the issue. 
* [This commit](https://github.com/jehanalvani/fustercluck/commit/abcdc19a67e9dff7f0234b857f17f69f423176d1#diff-09a6603843e7dc3d97f6dac4c73ebdd4212db3374a88c0a252db1c34081be0a2) converts network mode to host to workaround.

**Comment by samwiseg0** [comment]
This is not an issue with varken. You need to solve this issue on the Plex side. We only report with plex tells us. You will see this same behavior in tautulli.

**Comment by jehanalvani** [comment]
I have solved it, but laying out your requirements (eg. "Network mode must be host”) _or_ defining supported configurations seems prudent.

**Comment by samwiseg0** [comment]
That is not the only solution. If someone has a reverse proxy in front of Plex and they are in bridge mode it would work just fine as the proxy can pass the correct IP using headers. So making a blanket statement saying it should be X way would be incorrect. It is not the responsibility of this project to ensure someones Plex server is setup correctly.
