### ISSUE TITLE
[Feature Request] Write to multiple influxdb

### ISSUE THREAD

**Issue by DennisFaucher** [Boerderij/Varken#194]
**Is your feature request related to a problem? Please describe.**
Is it possible to have varken write to multiple instances of InfluxDB on separate servers?

**Describe the solution you'd like**
Add a comma delimited URL list to varken.ini

**Describe alternatives you've considered**

**Additional context**
Thank you

**Comment by samwiseg0** [comment]
Can you give some more information as to why you want this? I don’t really see why this is needed? 

You can always run 2 instances on varken

**Comment by DennisFaucher** [comment]
Good point. I'm just spoiled by telegram.conf where you can do that. Don't worry about it. Thanks for the response.

**Comment by samwiseg0** [comment]
Just to add to this... What you could do to make your life super easy is to deploy with docker compose and only set the influx config in the docker compose ENVs. Varken prioritizes the ENVs. What that allows you to do is use the same INI file for both instances so you only ever have to configure it once and any changes will be reflected on both. I have never tested that but in theory it should work.
