### ISSUE TITLE
[Feature Request] Consider using VictoriaMetrics instead of InfluxDB

### ISSUE THREAD

**Issue by valyala** [Boerderij/Varken#201]
**Is your feature request related to a problem? Please describe.**

While InfluxDB works great in most cases, sometimes it needs excess compute resources (RAM, CPU, disk IO, disk space) for certain workloads. In this case it would be better using alternative solutions such as VictoriaMetrics instead of InfluxDB, since it usually [needs lower compute resources than InfluxDB](https://docs.victoriametrics.com/Articles.html#benchmarks).

**Describe the solution you'd like**

To use VictoriaMetrics instead of InfluxDB. VictoriaMetrics supports data ingestion via Influx line protocol (see [these docs](https://docs.victoriametrics.com/#how-to-send-data-from-influxdb-compatible-agents-such-as-telegraf)), so it would be easy to to migrate from InfluxDB to VictoriaMetrics. It also supports [MetricsQL](https://victoriametrics.github.io/MetricsQL.html) - query language, which is better suited for creating typical monitoring graphs. The MetricsQL is backwards-compatible with PromQL - query language used in Prometheus, so VictoriaMetrics can be queried via Prometheus datasource in Grafana (see [these docs](https://docs.victoriametrics.com/#grafana-setup)). See [this PromQL tutorial](https://valyala.medium.com/promql-tutorial-for-beginners-9ab455142085) in order to feel the difference with InfluxQL or Flux.

**Comment by samwiseg0** [comment]
This does look interesting. 

* But is there really any benefit? They say it's "faster" and "better". But at the same time is there really an issue with using influx? I use influx for a ton of stuff on my network and I have no issues with resources or performance. As this may use "less" I don't think influx really uses that much that it would warrant a switch? If it is not something I would use myself I don't see the need to develop for it?
* Also there does not seem to be a python module for it? I would prefer not to have to write my own module. 
* They do have an "influx like" protocol but the documentation is not entirely clear what would have to change on our side? If it is as simple as enabling it why cant you just point Varken to their listener? The issue I would have with officially supporting it this way is when influx changes something and victoriametrics decides not to then our only choice that that point would be to either drop support for it or write something that is compatible. 
* We are open to PRs if someone want to add support for it but I don't know if there is much benefit? InfluxDB is ubiquitous and is much more supported by the community.

**Comment by samwiseg0** [comment]
I am going to close this since none of my questions were answered.

**Comment by danteali** [comment]
FYI there are no changes needed for Victoria Metrics - the VM address can simply be used in place of the influx endpoint.
