### ISSUE TITLE
[BUG] Library_stats Date Invalid

### ISSUE THREAD

**Issue by Subtixx** [Boerderij/Varken#211]
**Describe the bug**
The date of `SELECT distinct("total") FROM "Tautulli" WHERE ("type" = 'library_stats')`  returns as `1970-01-01 01:00:00`

**To Reproduce**
1. Fresh install of varken

**Expected behavior**

**Screenshots**

**Environment (please complete the following information):**
- Varken develop branch
- Tautulli v2.7.3

**Additional context**

**Comment by samwiseg0** [comment]
That means your date and time is Incorrect . We do not set any date/time statically. Please use our discord server for support

**Comment by Subtixx** [comment]
Date and time inside varken or inside tautulli? 

Tautulli charts show correct time. and time in varken is also set correctly. I dont think it has anything to do with my setup.

**Comment by samwiseg0** [comment]
@Subtixx issues is not the place for support. Please use our discord server
