### ISSUE TITLE
[BUG] TypeError due to missing arguments in develop branch

### ISSUE THREAD

**Issue by douginoz** [Boerderij/Varken#216]
I'm trying out the develop branch (I'm not a developer so bear with me) and it works for the most part, but returns 

ERROR : sonarr : TypeError has occurred : __new__() got an unexpected keyword argument 'sceneAbsoluteEpisodeNumber' while creating SonarrEpisode structure for show.

There are similar errors for a couple of other missing values.  I added them into structures.py, which resolves the errors:

    sceneAbsoluteEpisodeNumber: int = None
    sceneEpisodeNumber: int = None
    sceneSeasonNumber: int = None

**Comment by samwiseg0** [comment]
This fixed in develop.
