### ISSUE TITLE
Windows version to check on plex server local host

### ISSUE THREAD

**Issue by sojab0on** [Boerderij/Varken#219]
**Is your feature request related to a problem? Please describe.**
Windows version of Varken to pull data from a windows PMS not running in docker
**Describe the solution you'd like**
Varken Windows client to push PMS data to Influxdb server for grafana dashboard

**Describe alternatives you've considered**
Setting up a ubuntu mashine to run varken, but due pms not running in a docker but bare on windows i could not get info.

**Additional context**
Plex running bare on the windows os instead of in a docker due to a dedicated quadro GPU for 4k transcodes.
therefore varken in linux has issues with pulling data from the windows host, and i request a windows varken client that i can run on the same host to pull the data.

**Comment by samwiseg0** [comment]
Please read our documentation. Tautulli is required to pull data related to Plex. Varken does not speak to Plex directly. If you have further issues please use discord.
