### ISSUE TITLE
[Feature Request] Emby support

### ISSUE THREAD

**Issue by TRusselo** [Boerderij/Varken#228]
Emby support would be amazing.

A previous FR was closed due to not enough info provided.

**Additional context**
Emby is an open source project, their API documentation is here
 https://github.com/MediaBrowser/Emby/wiki
static api browser here
http://swagger.emby.media/?staticview=true
live api browser available within emby install as documented in the wiki above.

the Community forum is moderated by the developers. 
If you need something added to the API they will gladly help or let you fork in in the github.

https://emby.media/community/index.php
you want to be talking to Luke and EBR on the forum.

**Comment by samwiseg0** [comment]
The original request was closed because there is no stats software for emby.

Please see  https://github.com/Boerderij/Varken/issues/179

We have no plans to implement this ourselves but we are open to PRs given the requirement of polling a software much like Tautulli is fulfilled.
