### ISSUE TITLE
[Question] What is the influx url supposed to be? My hostname is invalid

### ISSUE THREAD

**Issue by Jleagle** [Boerderij/Varken#229]
My influx hostname is `influx` but i am getting this error in the logs..

`ERROR : iniparser : "influx" is invalid in module [influxdb]! URL must host/IP. ie. localhost`

My docker setup looks like: https://github.com/Jleagle/smart-home/blob/master/docker-compose.yml#L459

Thanks.

**Comment by samwiseg0** [comment]
Please use discord for support. 

Thanks
