### ISSUE TITLE
Security Vulnerabilities

### ISSUE THREAD

**Issue by samcro1967** [Boerderij/Varken#236]
Amazing work and love the product!  The current image has 49 Critical and High fixable security vulnerabilities.  Any plan to update the image in the near future?  From what I can tell, they are all related to the base image (python:3.9.1-alpine).  Thanks so much for your hard work.

**Comment by samwiseg0** [comment]
Can you be more specific as to what these security vulnerabilities are and how they affect this project?

**Comment by samcro1967** [comment]
Scan using the following:
```
curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sudo sh -s -- -b .
docker save boerderij/varken:latest --output varken.tar
grype --only-fixed docker-archive:./varken.tar | grep -i -E '(High|Critical)'
```
I did not share the list here as it is not generally considered good practice to publicly share security vulnerabilities of an application.

**Comment by samwiseg0** [comment]
> Scan using the following:
> 
> ```
> curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sudo sh -s -- -b .
> docker save boerderij/varken:latest --output varken.tar
> grype --only-fixed docker-archive:./varken.tar | grep -i -E '(High|Critical)'
> ```
> 
> I did not share the list here as it is not generally considered good practice to publicly share security vulnerabilities of an application.

Feel free to ping me on discord and we can discuss it further.
