### ISSUE TITLE
Feature Request  , Add Sickchill

### ISSUE THREAD

**Issue by CAVACO-PT** [Boerderij/Varken#48]
Feature Request  , Add Sickchill , when possivel !!!

**Comment by DirtyCajunRice** [comment]
totally for this. will need to brush up on sickchill api

**Comment by DirtyCajunRice** [comment]
added in last commit 
![image](https://user-images.githubusercontent.com/15788890/50050925-7dc6ff80-00cd-11e9-855f-c4988733f28c.png)
