### ISSUE TITLE
Ability to add custom tautulli port

### ISSUE THREAD

**Issue by chvvkumar** [Boerderij/Varken#49]
I run tautulli on a different port than port 80. Is there a way to add a custom port to the config without having to change the python script?

`requests.exceptions.ConnectionError: HTTPConnectionPool(host='docker.lan', port=80): Max retries exceeded with url: /api/v2?apikey=xxxxxxxxxx&cmd=get_activity (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f80156f6eb8>: Failed to establish a new connection: [Errno 111] Connection refused',))
`

**Comment by Grygon** [comment]
I'm having no problems just putting that under the url like so:

```
[tautulli-1]
url = tautulli:8181
```

**Comment by DirtyCajunRice** [comment]
@chvvkumar @Grygon is using the proper way

**Comment by chvvkumar** [comment]
Thank you, that works! I was expecting a seperate line for port specification based on how the other sections were setup :)
