### ISSUE TITLE
Feature Request - Include value from Radarr

### ISSUE THREAD

**Issue by source011** [Boerderij/Varken#50]
I would like to see the value "titleSlug" from the Radarr-request added in Influx as soon as the service runs. I don't need to update the field afterwards, I simply just need the "titleSlug" value.

**Comment by DirtyCajunRice** [comment]
@source011 so added as a column correct?

**Comment by samwiseg0** [comment]
Can you explain "Radarr-request added"?

**Comment by source011** [comment]
> @source011 so added as a column correct?

Yes as a column, sorry for not being specific.

**Comment by source011** [comment]
> Can you explain "Radarr-request added"?

Sorry, I meant to add the "titleSlug" from the GET-request from Radarr in to a column.

**Comment by samwiseg0** [comment]
@source011 I pushed a commit to nightly. Can you test it out and verify that is what you need?
