### ISSUE TITLE
Initial startup requires admin access to InfluxDB

### ISSUE THREAD

**Issue by dstidham617** [Boerderij/Varken#53]
No option to specify InfluxDB database to write to; database requirements are hard coded. Requires admin user to create the database. This can be mitigated by introducing a variable in the config.ini file to specify the database. Optionally, include additional steps needed in the README to pre-configure a database & user to avoid having to use an admin account. Steps should be identical for the Docker image, as well.

**Comment by DirtyCajunRice** [comment]
So, although database migrations are few and far in-between, Varken does intend to need to migrate databases which would require higher access than just one DB. This is something that would break an automated upgrade in the future. If you don't mind dropping the DB then creating again in your circumstance then its a non issue. We will add documentation to create the DB in the event that Varken's supplied user does not have administrative privileges.

Hopefully that is enough!
