### ISSUE TITLE
[Feature Request]: Pull list of requests (instead of just counts)

### ISSUE THREAD

**Issue by ethanopp** [Boerderij/Varken#58]
Would love to have a table in grafana that shows a list of requests currently pending.

Perhaps, the requester, date of request, and name of the movie/tv show

**Comment by GugZi** [comment]
I have done this with the old script, with movies and music, could not get it to work with shows..

**Comment by ethanopp** [comment]
Movies could be cool to start off with if the code is already written, does it pull status as well (Approved/Pending/Available/etc)?

**Comment by GugZi** [comment]
No but can do it maybe, can check it out later, but i only did it for the old script, did not try it with the new one

**Comment by DirtyCajunRice** [comment]
![image](https://user-images.githubusercontent.com/15788890/50049747-ab9e4b00-00b1-11e9-9770-910f828636d3.png)
Here is the push from tonight @ethanopp
