### ISSUE TITLE
[Feature Request] NZBHydra

### ISSUE THREAD

**Issue by rob1998** [Boerderij/Varken#69]
Is it possible to add NZBHydra stats to Varken,
That way I would be able to display stuff like downloads per indexer and indexer's success rates

**Comment by rob1998** [comment]
Yeah, I haven't worked with it before, but I'm sure I could figure it out.
It also works with torrent indexers btw
if you don't have the time to investigate it yourself, I can try to create a module myself. Has been a while since I've done Python, but I think I would be able to figure it out

**Comment by DirtyCajunRice** [comment]
So if you choose to make a module, please limit it to global stats. Doing per seed stats is literally recreating the torrent ui and defeats the purpose of grafana. We would love for a PR though! Rusty is better than no experience. Once you have made your initial pull, we will give any syntax or style changes we need and you will be good to go!

**Comment by rob1998** [comment]
Okay, I'll let you know if I need help or something.
Just FYI, I'm also looking at possible integration with Emby

**Comment by samwiseg0** [comment]
If you do start working on emby please open a new feature request so it can be tracked separately from this one.

**Comment by rob1998** [comment]
I will, it can take a while though. Don't have that much spare time 😅

**Comment by angryoso** [comment]
would it be nzbhydra or nzbhydra2,  I am running nzbhydra2 and would be willing to lend a hand/give access for testing

**Comment by rob1998** [comment]
I was going for nzbhydra2, since that makes the most sense. They added stats to their API in one of their latest commits

**Comment by DirtyCajunRice** [comment]
gonna close this out as there isnt any real push for it
