### ISSUE TITLE
[Feature Request] Add issues from Ombi

### ISSUE THREAD

**Issue by mastercpt** [Boerderij/Varken#70]
**Is your feature request related to a problem? Please describe.**
I get notifications from Ombi for issues but either don't have time to get to them or forget about them. A single point of information located on the dashboard of title and type or at minimum a count of open issues would be useful. 

**Describe the solution you'd like**
Add ability to grab issues from Ombi. At minimum a count would be good but also adding a table of request_type (tv/movie), status (pending, inprogress, resolved), Title, User reported would be nice. 

**Describe alternatives you've considered**
I get notifications already, but have to visit the Ombi page to view what the issue is. While this solution works, a single point of information would be better. 

**Additional context**
/api/v1/Issues/count
/api/v1/Issues

**Comment by DirtyCajunRice** [comment]
@mastercpt Issue counts have been added by @anderssonoscar0 . We decided against the full list. It should be available in the next release.
