### ISSUE TITLE
[Feature Request] ARMHF and ARM64 Docker Images

### ISSUE THREAD

**Issue by nemchik** [Boerderij/Varken#71]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Docker Images for ARMHF and ARM64. Multiarch on the main image so that everyone uses the same image name would be nice if possible.

**Describe alternatives you've considered**
Tags for the various architectures, or separate images if necessary.

**Additional context**
N/A

**Comment by DirtyCajunRice** [comment]
Just to update you, making a manifest with multiple dockerfiles and specifiying the armhf and arm64 is simple enough, and will allow for borderij/varken to pull your OS arch, but ive yet to conclude how to have dockerhub build them in an automated fashion without having a separate branch for each version (which is tedious and silly from an automation standpoint). When I break through that barrier Ill be able to move forward with this.

**Comment by DirtyCajunRice** [comment]
should be good to go. versioning to master now

**Comment by nemchik** [comment]
Amazing, thanks! I'll add the other architectures to my templates.
