### ISSUE TITLE
[BUG] unexpected keyword argument 'channel_icon'

### ISSUE THREAD

**Issue by ronaldreagan4prez** [Boerderij/Varken#73]
**Describe the bug**
When streaming live TV in Plex via the HDHR Viewer 2 plugin Varken fails to load the `channel_icon` key from Tautulli causing all metrics to be lost.

**To Reproduce**
1. Watch live TV via HDHR Viewer
2. Check Varken logs
3. Be sad when it's broken

**Expected behavior**
Varken should discard unexpected keys with a warning instead of a halt allowing metrics to be collected even in edge cases with custom configurations adding unknown keys to the stream.

**Screenshots**
`2018-12-26 19:14:19 : INFO : __init__ : Running job Every 30 seconds do threaded(<bound method TautulliAPI.get_activity of <tautulli-1>>) (last run: 2018-12-26 19:13:49, next run: 2018-12-26 19:14:19)
2018-12-26 19:14:19 : ERROR : tautulli : TypeError has occurred : __new__() got an unexpected keyword argument 'channel_icon' while creating TautulliStream structure`

**Environment (please complete the following information):**
 - OS: Docker:master
 - Version v1.4

**Additional context**
https://github.com/zynine-/HDHRViewerV2.bundle

**Comment by samwiseg0** [comment]
What is contained in `channel_icon`? Is it a string, integer, etc?

You can find the actual data in Tautulli by clicking in the word `STREAM` in the activity card.

**Comment by ronaldreagan4prez** [comment]
`channel_icon` is a string

Here is the output for the three `channel_*` keys -

`    "channel_icon": "http://resources-cdn.plexapp.com/image/source/com.plexapp.plugins.hdhrviewer.v2.jpg?h=None",
    "channel_stream": 1,
    "channel_title": "20:00 - 21:00: Anderson Cooper 360",`
