### ISSUE TITLE
[BUG] Worldmap Panel - Wrong Country

### ISSUE THREAD

**Issue by ShiroiKuma** [Boerderij/Varken#83]
**Describe the bug**
Los Angeles is being depicted for a user despite the user being on a private IP (10.25.0.0/24 range). And even then, if the public IP is resolved it should come to Japan.

**Expected behavior**
User A to be displayed as from Japan

**Screenshots**
N/A

**Environment (please complete the following information):**
Docker Image (latest as of 2019-01-03 12:00 UTC)

**Comment by ShiroiKuma** [comment]
Digging a bit further, it looks like the call to http://ip.42.pl/raw is routing through VPN possibly, I need to dig into that myself then.

**Comment by samwiseg0** [comment]
@ShiroiKuma You need to set your Public IP in the configuration. That will be removed in a future version. https://github.com/Boerderij/Varken/wiki/Configuration#tautulli-server-id

**Comment by ShiroiKuma** [comment]
@samwiseg0 Bad pfSense rule that was routing all traffic over a VPN, Destination/Source Port confusion.

On that note, I'll probably write a script to pull that from pfSense and then overwrite the file when it changes. Just not sure if Varken would need to be stopped or not to pick up the new ip.

**Comment by samwiseg0** [comment]
@ShiroiKuma Please read the failback IP documentation. https://github.com/Boerderij/Varken/wiki/Configuration#tautulli-server-id

You do not need to change that value. You would need to restart the service if you change the config.
