### ISSUE TITLE
Invalid Syntax from the ombi.py file

### ISSUE THREAD

**Issue by hotleadsingerguy** [Boerderij/Varken#89]
Followed installation instructions and I get an invalid syntax exception trying to launch it, coming from line 19 of the ombi.py file:

```
File "/opt/Varken/Varken.py", line 13, in <module>
   from varken.ombi import OmbiAPI
File "/opt/Varken/varken/ombi.py", line 19
   return f"<ombi-{self.server.id}>"
                                                     ^
```

**Comment by hotleadsingerguy** [comment]
OK, no matter how I format it it doesn't work... the "^" carat is directly below the last double-quote character.

**Comment by DirtyCajunRice** [comment]
This is not a bug, this is troubleshooting. Please join the discord for support

**Comment by samwiseg0** [comment]
Also review the configuration documentation in the wiki. 

https://github.com/Boerderij/Varken/wiki/Configuration

**Comment by hotleadsingerguy** [comment]
The Discord link is broken/expired. Do you have an updated one?
