### ISSUE TITLE
[BUG] SyntaxError: invalid syntax during linux install

### ISSUE THREAD

**Issue by svenvg93** [Boerderij/Varken#98]
**Describe the bug**
While running _/opt/Varken/varken-venv/bin/python /opt/Varken/Varken.py_  during install I get the follow error:

 File "/opt/Varken/Varken.py", line 101
    at_time.do(QUEUE.put, SONARR.get_queue).tag(f"sonarr-{server.id}-get_queue")
                                                                                                                                          ^
SyntaxError: invalid syntax

**To Reproduce**
1. Follow install instructies for linux
2. Run /opt/Varken/varken-venv/bin/python /opt/Varken/Varken.py 

**Expected behavior**

**Environment (please complete the following information):**
 - OS: Debian 9
 - Version 

**Additional context**

**Comment by samwiseg0** [comment]
Issues is not the place for support. Please use [Discord](https://discord.gg/VjZ6qSM) for support.
