### ISSUE TITLE
[BUG] does not launch

### ISSUE THREAD

**Issue by hagabla** [Boerderij/Varken#99]
**Describe the bug**
varken errors out with syntax error on launch
**To Reproduce**
1. install it following the wiki
2. try to launch

**Screenshots**
`/opt/Varken/varken-venv/bin/python /opt/Varken/Varken.py`
```
  File "/opt/Varken/Varken.py", line 101
    at_time.do(QUEUE.put, SONARR.get_queue).tag(f"sonarr-{server.id}-get_queue")
                                                                              ^
SyntaxError: invalid syntax

```
**Environment (please complete the following information):**
 - OS: Debian 9

**Comment by samwiseg0** [comment]
Issues is not the place for support. Please use discord. 

P.s you are more than likely not running the correct version of python. https://github.com/Boerderij/Varken/wiki/Frequently-Asked-Questions#general-q7

**Comment by hagabla** [comment]
Thats most likely it, thanks, but i do not see any official debian packages for stable higher than 3.5.
